name: novinarko
description: News app made in Flutter
publish_to: 'none'
version: 1.0.2+102

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: 3.3.1
  dio: 5.4.1
  easy_localization: 3.0.5
  envied: 0.5.3
  flutter_animate: 4.5.0
  flutter_swipe_action_cell: 3.1.3
  flutter_web_browser: 0.17.1
  get_it: 7.6.7
  hive: 2.2.3
  hive_flutter: 1.1.0
  html: 0.15.4
  intl: 0.19.0
  just_audio: 0.9.36
  loading_animation_widget: 1.2.0+4
  logger: 2.1.0
  rss_dart: 1.0.6
  timeago: 3.6.1
  url_launcher: 6.2.5
  watch_it: 1.4.0
  webview_flutter: 4.7.0

dev_dependencies:
  build_runner: 2.4.8
  envied_generator: 0.5.3
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.13
  hive_generator: 2.0.1

dependency_overrides:
  intl: 0.19.0

  # Run code generation - `dart run build_runner build -d`

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'dart run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#F2F2F2'
  adaptive_icon_foreground: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'dart run flutter_native_splash:create'
flutter_native_splash:
  android: true
  ios: true
  color: '#F2F2F2'
  color_dark: '#444B6E'
  android_12:
    color: '#F2F2F2'
    color_dark: '#444B6E'

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/fonts/
    - assets/icons/
    - assets/translations/
  fonts:
    - family: EncodeSans
      fonts:
        - asset: assets/fonts/EncodeSans/EncodeSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/EncodeSans/EncodeSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/EncodeSans/EncodeSans-Light.ttf
          weight: 300
        - asset: assets/fonts/EncodeSans/EncodeSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/EncodeSans/EncodeSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/EncodeSans/EncodeSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/EncodeSans/EncodeSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/EncodeSans/EncodeSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/EncodeSans/EncodeSans-Black.ttf
          weight: 900
    - family: SongMyung
      fonts:
        - asset: assets/fonts/SongMyung/SongMyung-Regular.ttf
          weight: 400
