name: novinarko
description: News app made in Flutter
publish_to: 'none'
version: 1.2.5+125

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: 3.3.1
  dio: 5.4.3+1
  dough: 2.0.0
  easy_localization: 3.0.7
  envied: 0.5.4+1
  flutter_animate: 4.5.0
  flutter_inappwebview: 6.0.0
  flutter_swipe_action_cell: 3.1.3
  flutter_web_browser: 0.17.1
  get_it: 7.7.0
  hive: 2.2.3
  hive_flutter: 1.1.0
  html: 0.15.4
  intl: 0.19.0
  just_audio: 0.9.38
  loading_animation_widget: 1.2.1
  logger: 2.3.0
  package_info_plus: 8.0.0
  path_provider: 2.1.3
  preload_page_view: 0.2.0
  sentry_flutter: 8.2.0
  timeago: 3.6.1
  url_launcher: 6.2.6
  watch_it: 1.4.2
  xml: 6.5.0

dev_dependencies:
  build_runner: 2.4.10
  envied_generator: 0.5.4+1
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.4.0
  hive_generator: 2.0.1

  # Run code generation - `dart run build_runner build -d`

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'dart run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#F2E2BA'
  adaptive_icon_foreground: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'dart run flutter_native_splash:create'
flutter_native_splash:
  android: true
  ios: true
  color: '#F2E2BA'
  color_dark: '#444B6E'
  android_12:
    color: '#F2E2BA'
    color_dark: '#444B6E'

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/fonts/
    - assets/icons/
    - assets/translations/
  fonts:
    - family: EncodeSans
      fonts:
        - asset: assets/fonts/EncodeSans/EncodeSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/EncodeSans/EncodeSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/EncodeSans/EncodeSans-Light.ttf
          weight: 300
        - asset: assets/fonts/EncodeSans/EncodeSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/EncodeSans/EncodeSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/EncodeSans/EncodeSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/EncodeSans/EncodeSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/EncodeSans/EncodeSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/EncodeSans/EncodeSans-Black.ttf
          weight: 900
    - family: SongMyung
      fonts:
        - asset: assets/fonts/SongMyung/SongMyung-Regular.ttf
          weight: 400
