name: novinarko
description: News app made in Flutter
publish_to: 'none'
version: 1.5.0+150

environment:
  sdk: 3.6.0

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: 3.4.1
  dio: 5.7.0
  dough: 2.0.0
  easy_localization: 3.0.7
  envied: 1.0.0
  flutter_animate: 4.5.2
  flutter_inappwebview: 6.1.5
  flutter_swipe_action_cell: 3.1.5
  flutter_web_browser: 0.17.1
  get_it: 8.0.3
  hive_ce: 2.8.0+3
  hive_ce_flutter: 2.2.0
  html: 0.15.4
  internet_connection_checker_plus: 2.7.0
  intl: 0.20.1
  just_audio: 0.9.42
  loading_animation_widget: 1.3.0
  logger: 2.5.0
  package_info_plus: 8.1.2
  path_provider: 2.1.5
  preload_page_view: 0.2.0
  sentry_flutter: 8.12.0
  share_plus: 10.1.3
  timeago: 3.7.0
  url_launcher: 6.3.1
  watch_it: 1.6.1
  xml: 6.5.0

dev_dependencies:
  build_runner: 2.4.14
  envied_generator: 1.0.0
  flutter_launcher_icons: 0.14.2
  flutter_native_splash: 2.4.4
  hive_ce_generator: 1.8.1

dependency_overrides:
  intl: 0.20.1

# Run code generation - `dart run build_runner build -d`

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/fonts/
    - assets/icons/
    - assets/translations/
  fonts:
    - family: EncodeSans
      fonts:
        - asset: assets/fonts/EncodeSans/EncodeSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/EncodeSans/EncodeSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/EncodeSans/EncodeSans-Light.ttf
          weight: 300
        - asset: assets/fonts/EncodeSans/EncodeSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/EncodeSans/EncodeSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/EncodeSans/EncodeSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/EncodeSans/EncodeSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/EncodeSans/EncodeSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/EncodeSans/EncodeSans-Black.ttf
          weight: 900
    - family: SongMyung
      fonts:
        - asset: assets/fonts/SongMyung/SongMyung-Regular.ttf
          weight: 400

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'dart run flutter_launcher_icons:main'
flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  min_sdk_android: 21
  adaptive_icon_background: '#F2E2BA'
  adaptive_icon_foreground: 'assets/icon.png'
  web:
    generate: true
    image_path: 'assets/icon.png'
    background_color: '#F2E2BA'
    theme_color: '#F2E2BA'
  windows:
    generate: true
    image_path: 'assets/icon.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'dart run flutter_native_splash:create'
flutter_native_splash:
  background_image: "assets/splash.png"
  background_image_dark: "assets/splash_dark.png"
  android_12:
    image: assets/splash_icon.png
    color: "#F2E2BA"
    image_dark: assets/splash_icon.png
    color_dark: "#444B6E"
